version: '3.8'
services:
  app:
    build: .
     # volumes:
     #  - .:/usr/src/app
     # - prisma-db-volume:/usr/src/app/prisma
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://johndoe:randompassword@db:5432/mydb?schema=public
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - prisma-postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

volumes:
  prisma-postgres-volume:
