name: Publish Docker Image
on:
  push:
    branches:
      - 'master'
jobs:
  public_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t tidan/app:latest
      - name: publish
        run: |
          docker login -u tidan -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push tidan/app:latest